name: tests
on:
  push:
    branches:
      - master
  pull_request:
    branches-ignore:
      - i18n_master

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    services:
      postgres:
        image: postgres:10.10
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        env:
          POSTGRES_USER: consul
          POSTGRES_PASSWORD: ""
    env:
      CI_BUILD_NUMBER: ${{ github.run_number }}
      COVERALLS_FLAG_NAME: run-${{ matrix.ci_node_index }}
      COVERALLS_PARALLEL: true
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      PGUSER: consul
      POSTGRES_HOST: postgres
      RAILS_ENV: test
    strategy:
      fail-fast: false
      matrix:
        ci_node_total: [5]
        ci_node_index: [0, 1, 2, 3, 4]
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup NPM
        uses: actions/setup-node@v1
      - name: Copy secrets and database files
        run: for i in config/*.example; do cp "$i" "${i/.example}"; done
      - name: Setup database
        run: bundle exec rake db:setup
      - name: Compile assets
        run: bundle exec rake assets:precompile > /dev/null 2>&1
      - name: Run test suite
        env:
          CI_NODE_TOTAL: ${{ matrix.ci_node_total }}
          CI_NODE_INDEX: ${{ matrix.ci_node_index }}
        run: bundle exec rake knapsack:rspec
      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: tmp/screenshots
  coveralls:
    runs-on: ubuntu-latest
    needs: tests
    env:
      CI_BUILD_NUMBER: ${{ github.run_number }}
      COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
    steps:
      - name: Finish coveralls
        run: curl -k https://coveralls.io/webhook?repo_token=$COVERALLS_REPO_TOKEN -d "payload[build_num]=$CI_BUILD_NUMBER&payload[status]=done"
